### ISSUE TITLE
Fix intro video (cutscene) background

### ISSUE THREAD

**Issue by Kaffeine** [WiredForWar/machines-archived#13]
Updated by Matthew 09/15/2022
## Tasklist:

- [x] Add call to "clear" the framebuffer in between logo images & intro cutscene in MachGuiStartupScreens
- [x] Update framescaler to preserve aspect ratio when upscaling: <br> W = Screen width, 
![CodeCogsEqn](https://user-images.githubusercontent.com/35634280/190435741-597bdad0-ab2f-4636-beee-b84b5a8112f3.gif)

## Issue:
Right now some spikes from the Charybdis logo are rendered behind. I think it is weird, and the background should be solid black.

![image](https://user-images.githubusercontent.com/374839/186776777-9b80daa4-09a4-43ae-8107-59e940a0f6b3.png)

**Comment by m-flak** [comment]
They don't "clear" the buffer before drawing frames in the menus, so those
few pixels from the logo are still there each frame. It's the whole reason
why blitBackdrop existed, because the buffer is never cleared with a nice
solid black.

If you know where the 2D renders start, you could try "clearing" the buffer
before the subsequent draws.

**Comment by m-flak** [comment]
I think I know how & where to fix this. How do I turn off the scaling? With a cmake option? A define?

**Comment by Kaffeine** [comment]
There is no exposed option for that. See https://github.com/WiredForWar/machines/blob/15ad7534ffd9f962b3ed3a634044755ed2ab0c6b/CMakeLists.txt#L141-L142

You can comment-out `find_package(SWScale)` but probably you'll have to reconfigure the project because the target maybe cached. Easier option is replace `set(USE_SWSCALE ${SWScale_FOUND})` with `set(USE_SWSCALE FALSE)`.

**Comment by Kaffeine** [comment]
While you're there, it would be nice to fix the aspect-ratio. 😇 
Right now we do "stretch" but probably we want to "fit preserving aspect".

**Comment by m-flak** [comment]
> While you're there, it would be nice to fix the aspect-ratio. 😇 Right now we do "stretch" but probably we want to "fit preserving aspect".

O͞oh! That would make this a fun problem to solve. 

Another question: Did you ever figure out what caused the choppy sound?

**Comment by Kaffeine** [comment]
> Did you ever figure out what caused the choppy sound?

I tried to but I could not find the root of the problem. I assumed some issues but could not confirm them (so the problem is different).

---
Also, the videos taking 331.4 MiB of the download size. It would be cool to switch to some modern format and get much smaller size (assuming there is no visual difference). E.g. converting to mp4 (using libx264) gives no visible difference and 4.5 smaller files.
Probably we want something more open and free, such as WebM. I have yet to find the params to get similar quality.

It would be better for distribution if the users 'll have to download 200 MiB for the game, instead of current 411+512 MiB (original assets + HQ textures).

The different codec is a long-term 'maybe' wanted feature; fixing the sound right now would be very nice.

**Comment by m-flak** [comment]
Task 1: Issue was found in RenDevice. It never actually cleared anything.
